"""
CrewAI Agents — the three triage specialists
============================================

Each agent maps to one step the sequential pipeline already performed, but
as an autonomous role with its own goal, backstory and tools rather than a
hardcoded function call. The value of modelling it this way is not speed —
the benchmark shows it is slower (docs/benchmarks/crew-vs-sequential.md) —
it is that adding a fourth specialist, or letting one agent request more
information from another, becomes a configuration change rather than a
rewrite of the endpoint.

LLM
  Groq llama-3.3-70b-versatile by default, via CrewAI's litellm wrapper.
  Model name is `groq/<model>` because litellm routes on the provider prefix,
  unlike the bare `llama-3.3-70b-versatile` the triage and chatbot services
  pass to the Groq SDK directly.

  CREW_MODEL also accepts a `bedrock/<model-id>` prefix — e.g.
  `bedrock/anthropic.claude-3-haiku-20240307-v1:0` — which litellm routes to
  AWS Bedrock using boto3's normal credential chain (env vars, shared config,
  or an IAM role if this ever runs on AWS compute). No code branch is needed
  for that switch; only build_llm()'s *readiness check* differs by provider,
  since Bedrock has no single "is it configured" env var the way Groq does.
  See docs/crewai-integration.md and docs/benchmarks/bedrock-vs-groq.md
  (pending — generated by benchmark_bedrock.py, needs real Bedrock credentials).

DELEGATION IS OFF
  allow_delegation=False on all three. With it enabled, an agent that
  struggles can hand its task to another, which sounds appealing but means
  the classifier could end up writing cost estimates without ever calling
  the XGBoost tool. The whole point of this design is that the deterministic
  work stays deterministic, so each agent owns exactly its own step.
"""

import logging
import os

from crewai import LLM, Agent

from tools import classify_inquiry_tool, estimate_cost_tool, recommend_technician_tool

logger = logging.getLogger("crew.agents")

CREW_MODEL = os.getenv("CREW_MODEL", "groq/llama-3.3-70b-versatile")
CREW_TEMPERATURE = float(os.getenv("CREW_TEMPERATURE", "0.1"))
CREW_MAX_ITER = int(os.getenv("CREW_MAX_ITER", "5"))


def llm_provider(model: str = CREW_MODEL) -> str:
    """The litellm provider prefix — "groq", "bedrock", etc."""
    return model.split("/", 1)[0] if "/" in model else "groq"


def llm_backend_ready(model: str = CREW_MODEL) -> bool:
    """Best-effort readiness check, used by /crew/health and by build_llm().

    Groq has one env var, so its check is exact. Bedrock has no equivalent —
    boto3's credential chain resolves at call time from any of an access
    key pair, a shared ~/.aws/credentials profile, or an attached IAM role,
    and there is no single variable whose absence definitively means
    "will fail". Reporting True here is honestly "credentials might exist
    somewhere in the chain", not "verified working" — the only real
    verification is build_llm() succeeding, and ultimately a call to Bedrock
    actually returning.
    """
    provider = llm_provider(model)
    if provider == "groq":
        return bool(os.getenv("GROQ_API_KEY"))
    if provider == "bedrock":
        return bool(
            os.getenv("AWS_ACCESS_KEY_ID")
            or os.getenv("AWS_PROFILE")
            or os.getenv("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI")  # ECS/Lambda role
        )
    # Unknown provider — don't claim readiness we can't check for.
    return False


def build_llm(model: str | None = None) -> LLM | None:
    """Construct the shared LLM, or None if it isn't configured or fails.

    Mirrors the never-raise contract of get_groq_client() in
    services/triage/main.py — a missing credential degrades the service to a
    clean 503 rather than raising at import time and taking the whole app
    down. Works the same way regardless of provider: the model string's
    prefix is all litellm needs to route the call correctly.

    `model` defaults to CREW_MODEL (the env-configured value main.py uses)
    but can be overridden per call — benchmark_bedrock.py uses this to build
    a Groq LLM and a Bedrock LLM side by side in one process, without an
    env var + module reload dance.
    """
    model = model or CREW_MODEL
    if not llm_backend_ready(model):
        logger.warning(
            f"No credentials found for provider '{llm_provider(model)}' "
            f"(model={model}) — crew will be unavailable"
        )
        return None
    try:
        return LLM(model=model, temperature=CREW_TEMPERATURE)
    except Exception as exc:  # noqa: BLE001 - never take the service down
        logger.warning(f"LLM init failed: {exc} — crew will be unavailable")
        return None


def build_agents(llm: LLM) -> tuple[Agent, Agent, Agent]:
    """Build the three triage agents sharing one LLM instance."""

    classifier = Agent(
        role="Customer Inquiry Classification Specialist",
        goal=(
            "Accurately classify the service type, urgency, equipment involved "
            "and location from a customer's raw inquiry text."
        ),
        backstory=(
            "You have spent fifteen years on the phones at a South African "
            "electrical and refrigeration firm. You can tell the difference "
            "between a customer who is mildly inconvenienced and one whose "
            "cold room is quietly destroying R80,000 of stock, and you know "
            "that 'the lights are doing a funny thing' can mean anything from "
            "a loose neutral to an arcing distribution board."
        ),
        llm=llm,
        tools=[classify_inquiry_tool],
        allow_delegation=False,
        max_iter=CREW_MAX_ITER,
        verbose=True,
    )

    cost_estimator = Agent(
        role="Service Cost Estimation Specialist",
        goal=(
            "Produce an accurate, data-driven cost range for the classified job "
            "using the trained estimation model, and explain the drivers behind it."
        ),
        backstory=(
            "You price jobs for a living and you have been burned by guesswork. "
            "You never estimate from intuition when a model trained on completed "
            "job history is available, and you report its figures exactly as "
            "returned — a quote that drifts from the model is a quote that "
            "cannot be defended to a customer or an auditor."
        ),
        llm=llm,
        tools=[estimate_cost_tool],
        allow_delegation=False,
        max_iter=CREW_MAX_ITER,
        verbose=True,
    )

    technician_matcher = Agent(
        role="Technician Assignment Specialist",
        goal=(
            "Match the job to the technicians best placed to complete it, "
            "balancing skill fit, current workload and familiarity with the area."
        ),
        backstory=(
            "You run dispatch across Gauteng and Limpopo. You know that the "
            "most skilled technician is the wrong answer when they already have "
            "four jobs open, and that someone who has worked a suburb for years "
            "finds the property faster than a stranger with a map."
        ),
        llm=llm,
        tools=[recommend_technician_tool],
        allow_delegation=False,
        max_iter=CREW_MAX_ITER,
        verbose=True,
    )

    return classifier, cost_estimator, technician_matcher
